import type { Finding, IntentMatch, Verdict } from "@/lib/db/types";
import type { SkippedFile } from "@/lib/db/types";

const VERDICT_BANNER: Record<Verdict, string> = {
  APPROVE: "APPROVED ✅",
  REQUEST_CHANGES: "CHANGES REQUESTED 🔴",
  COMMENT: "COMMENTS 💬",
};

const SEVERITY_ICON: Record<Finding["severity"], string> = {
  critical: "🔴",
  major: "🟠",
  minor: "🟡",
  nit: "⚪",
};

function intentLine(intent: IntentMatch): string {
  if (intent.status === "match") {
    return "**Intent**: ✅ Title & description match the changes";
  }
  if (intent.status === "partial") {
    return `**Intent**: ⚠️ Partial — ${intent.explanation}`;
  }
  return `**Intent**: 🔴 Mismatch — ${intent.explanation}`;
}

export interface SummaryInput {
  verdict: Verdict;
  summary: string;
  intentMatch: IntentMatch;
  findings: Finding[];
  filesReviewed: number;
  skippedFiles: SkippedFile[];
  shortSha: string;
  newerCommits: boolean;
  model: string;
}

export function buildReviewBody(input: SummaryInput): string {
  const counts = {
    critical: input.findings.filter((f) => f.severity === "critical").length,
    major: input.findings.filter((f) => f.severity === "major").length,
    minor: input.findings.filter((f) => f.severity === "minor").length,
  };

  const parts: string[] = [
    `## 🤖 AI Review — ${VERDICT_BANNER[input.verdict]}`,
    "",
    "**Summary**",
    input.summary,
    "",
    intentLine(input.intentMatch),
    "",
    `**Stats**: ${input.filesReviewed} files reviewed · ${input.findings.length} findings (${counts.critical} critical, ${counts.major} major, ${counts.minor} minor) · commit \`${input.shortSha}\``,
  ];

  if (input.findings.length > 0) {
    parts.push(
      "",
      "| Severity | File | Issue |",
      "|---|---|---|",
      ...input.findings.map(
        (f) =>
          `| ${SEVERITY_ICON[f.severity]} ${f.severity} | \`${f.path}:${f.line}\` | ${f.comment.replace(/\n/g, " ").slice(0, 140)} |`,
      ),
    );
  }

  if (input.skippedFiles.length > 0) {
    const list = input.skippedFiles
      .map((s) => `- \`${s.path}\` — ${s.reason}`)
      .join("\n");
    parts.push(
      "",
      `<details><summary>Files not reviewed (${input.skippedFiles.length})</summary>\n\n${list}\n</details>`,
    );
  }

  if (input.newerCommits) {
    parts.push(
      "",
      `> ⚠️ Commits were pushed after \`${input.shortSha}\`. Re-request review to cover the latest changes.`,
    );
  }

  parts.push("", `<sub>Generated by PR Reviewer · ${input.model}</sub>`);
  return parts.join("\n");
}
