// PR Reviewer brutalist kit — window.PRR. Types are documentation.
import * as React from 'react';
type Btn = React.ButtonHTMLAttributes<HTMLButtonElement>;
export type ButtonProps = Btn & { variant?: 'primary' | 'secondary' | 'destructive' | 'ghost'; size?: 'sm' | 'md' | 'icon'; loading?: boolean };
export declare const Button: React.ForwardRefExoticComponent<ButtonProps & React.RefAttributes<HTMLButtonElement>>;
export type BadgeProps = React.HTMLAttributes<HTMLSpanElement> & { variant?: 'success' | 'warning' | 'error' | 'info' | 'neutral' | 'accent' };
export declare function Badge(p: BadgeProps): React.ReactElement;
export type CardProps = React.HTMLAttributes<HTMLDivElement> & { hoverLift?: boolean; kicker?: React.ReactNode; title?: React.ReactNode };
export declare function Card(p: CardProps): React.ReactElement;
export declare const GlassCard: typeof Card;
type FieldProps = { label?: string; hint?: string; error?: string; containerClassName?: string };
export type InputProps = React.InputHTMLAttributes<HTMLInputElement> & FieldProps;
export declare const Input: React.ForwardRefExoticComponent<InputProps & React.RefAttributes<HTMLInputElement>>;
export type PasswordInputProps = Omit<InputProps, 'type'>;
export declare const PasswordInput: React.ForwardRefExoticComponent<PasswordInputProps & React.RefAttributes<HTMLInputElement>>;
export type TextareaProps = React.TextareaHTMLAttributes<HTMLTextAreaElement> & FieldProps & { minHeight?: number };
export declare const Textarea: React.ForwardRefExoticComponent<TextareaProps & React.RefAttributes<HTMLTextAreaElement>>;
export type SelectOption = { value: string; label: React.ReactNode; disabled?: boolean };
export type SelectProps = FieldProps & { options: SelectOption[]; value?: string; defaultValue?: string; placeholder?: string; name?: string; disabled?: boolean; id?: string; className?: string; 'aria-label'?: string; defaultOpen?: boolean;
  onChange?: (e: { target: { value: string; name?: string }; currentTarget: { value: string; name?: string } }) => void; onValueChange?: (value: string) => void };
export declare const Select: React.ForwardRefExoticComponent<SelectProps & React.RefAttributes<HTMLButtonElement>>;
export type CheckboxProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> & { label?: React.ReactNode };
export declare const Checkbox: React.ForwardRefExoticComponent<CheckboxProps & React.RefAttributes<HTMLInputElement>>;
export type RadioGroupProps = { label?: string; name?: string; options: { value: string; label: React.ReactNode; disabled?: boolean }[]; value?: string; defaultValue?: string; onValueChange?: (v: string) => void; orientation?: 'vertical' | 'horizontal'; disabled?: boolean; className?: string };
export declare function RadioGroup(p: RadioGroupProps): React.ReactElement;
export type SwitchProps = Omit<Btn, 'onChange'> & { label?: string; checked?: boolean; defaultChecked?: boolean; onCheckedChange?: (v: boolean) => void };
export declare const Switch: React.ForwardRefExoticComponent<SwitchProps & React.RefAttributes<HTMLButtonElement>>;
export type SliderProps = { label?: string; min?: number; max?: number; step?: number; value?: number | number[]; defaultValue?: number | number[]; onValueChange?: (v: number | number[]) => void; format?: (v: number) => React.ReactNode; disabled?: boolean; id?: string; className?: string };
export declare function Slider(p: SliderProps): React.ReactElement;
export type DialogProps = { open: boolean; onOpenChange?: (open: boolean) => void; title?: React.ReactNode; description?: React.ReactNode; showClose?: boolean; role?: 'dialog' | 'alertdialog'; className?: string; children?: React.ReactNode };
export declare function Dialog(p: DialogProps): React.ReactElement | null;
export type ConfirmDialogProps = { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel?: string; cancelLabel?: string; destructive?: boolean; onConfirm: () => void; loading?: boolean };
export declare function ConfirmDialog(p: ConfirmDialogProps): React.ReactElement | null;
export type DropdownMenuProps = { trigger: React.ReactElement; align?: 'start' | 'end'; defaultOpen?: boolean; className?: string; children?: React.ReactNode };
export declare function DropdownMenu(p: DropdownMenuProps): React.ReactElement;
export type DropdownMenuItemProps = Btn & { destructive?: boolean; onSelect?: (e: React.MouseEvent) => void };
export declare function DropdownMenuItem(p: DropdownMenuItemProps): React.ReactElement;
export declare function DropdownMenuLabel(p: { children?: React.ReactNode }): React.ReactElement;
export declare function DropdownMenuSeparator(): React.ReactElement;
export type TooltipProps = { content: React.ReactNode; children: React.ReactElement; side?: 'top' | 'bottom'; delayDuration?: number; className?: string };
export declare function Tooltip(p: TooltipProps): React.ReactElement;
export declare function Skeleton(p: React.HTMLAttributes<HTMLSpanElement>): React.ReactElement;
export declare function Toaster(p: {}): React.ReactElement;
export declare const AppToaster: typeof Toaster;
type T = (message: string, description?: string, opts?: { duration?: number }) => number;
export declare const toast: { success: T; error: T; warning: T; info: T; loading: (message: string) => number; dismiss: (id?: number) => void };

// ---------- Dashboard layer ----------
export type IconName = 'dashboard' | 'pr' | 'chart' | 'folder' | 'settings' | 'chevronLeft' | 'chevronRight' | 'chevronDown' | 'arrowLeft' | 'bell' | 'sun' | 'moon' | 'menu' | 'more' | 'logout' | 'refresh' | 'alert' | 'clock' | 'wifiOff' | 'check' | 'checkCheck' | 'external' | 'download' | 'fork' | 'building' | 'user' | 'plug' | 'search' | 'x' | 'plus';
export declare function Icon(p: { name: IconName; size?: number; strokeWidth?: number; label?: string; className?: string }): React.ReactElement;
export declare const ICON_NAMES: IconName[];
type IconLike = IconName | React.ReactElement;
export type NavItem = { label: string; href: string; icon?: IconLike; badge?: React.ReactNode; active?: boolean };
export type AdminMenuProps = { name?: string; email?: string; initials?: string; collapsed?: boolean; onLogout?: () => void; loggingOut?: boolean };
export declare function AdminMenu(p: AdminMenuProps): React.ReactElement;
export type ChangelogEntry = { version: string; date: string; title: string; changes: string[] };
export declare function Popover(p: { trigger: React.ReactElement; children: React.ReactNode | ((close: () => void) => React.ReactNode); open?: boolean; defaultOpen?: boolean; onOpenChange?: (o: boolean) => void; align?: 'start' | 'end'; side?: 'bottom' | 'top'; label?: string; className?: string }): React.ReactElement;
export declare function BrandMark(p: { name?: string; compact?: boolean }): React.ReactElement;
export declare function ThemeToggle(p: { theme?: 'light' | 'dark'; onThemeChange?: (t: 'light' | 'dark') => void; tooltipSide?: 'top' | 'bottom' | 'right' }): React.ReactElement;
export type SystemStatus = 'healthy' | 'degraded' | 'down';
export declare function StatusDot(p: { status?: SystemStatus; label?: string; tooltip?: string; hideLabel?: boolean }): React.ReactElement;
export declare function LiveIndicator(p: { label?: string; ariaLabel?: string }): React.ReactElement;
export declare function WhatsNew(p: { entries: ChangelogEntry[]; unread?: boolean; onSeen?: () => void; subtitle?: string; defaultOpen?: boolean }): React.ReactElement;
export declare function Avatar(p: { name?: string; src?: string; size?: number; initials?: string; tone?: 'accent' }): React.ReactElement;
export type SidebarProps = { items?: NavItem[]; activeHref?: string; collapsed?: boolean; defaultCollapsed?: boolean; onCollapsedChange?: (v: boolean) => void; onNavigate?: (item: NavItem) => void; admin?: AdminMenuProps; footer?: React.ReactNode; mobile?: boolean; onClose?: () => void; brandName?: string };
export declare function Sidebar(p: SidebarProps): React.ReactElement;
export type HeaderProps = { title?: React.ReactNode; onMenuClick?: () => void; changelog?: ChangelogEntry[] | false; unread?: boolean; status?: SystemStatus; theme?: 'light' | 'dark'; onThemeChange?: (t: 'light' | 'dark') => void; actions?: React.ReactNode };
export declare function Header(p: HeaderProps): React.ReactElement;
export type AppShellProps = { title?: React.ReactNode; activeHref?: string; navItems?: NavItem[]; onNavigate?: (item: NavItem) => void; changelog?: ChangelogEntry[]; status?: SystemStatus; headerActions?: React.ReactNode; admin?: AdminMenuProps; defaultCollapsed?: boolean; brandName?: string; children?: React.ReactNode };
export declare function AppShell(p: AppShellProps): React.ReactElement;
export declare function PageHeader(p: { title: React.ReactNode; description?: React.ReactNode; kicker?: React.ReactNode; badge?: React.ReactNode; actions?: React.ReactNode; onBack?: () => void; backLabel?: string }): React.ReactElement;
export declare function SectionHeading(p: { children: React.ReactNode; count?: number; action?: React.ReactNode; as?: 'h2' | 'h3' }): React.ReactElement;
export declare function StatCard(p: { label?: string; value?: React.ReactNode; icon?: IconLike; delta?: string; hint?: string; loading?: boolean; hoverLift?: boolean }): React.ReactElement;
export declare function SummaryCard(p: { label?: string; value?: React.ReactNode; loading?: boolean }): React.ReactElement;
export declare function BudgetMeter(p: { spent: number; limit: number; format?: (v: number) => string; label?: string; overMessage?: string }): React.ReactElement;
export type AttentionTone = 'warning' | 'error' | 'neutral' | 'success';
export declare function AttentionItem(p: { tone?: AttentionTone; icon?: IconLike; title: React.ReactNode; tags?: string[]; action?: { label: string; href?: string; onClick?: (e: React.MouseEvent) => void } }): React.ReactElement;
export declare function AttentionList(p: { children?: React.ReactNode; emptyText?: string }): React.ReactElement;
export declare function EmptyState(p: { title?: string; description?: string; icon?: IconLike; action?: React.ReactNode }): React.ReactElement;
export declare function ErrorState(p: { title?: string; message?: string; onRetry?: () => void }): React.ReactElement;
export type Column<R> = { key: string; header: React.ReactNode; render?: (row: R) => React.ReactNode; align?: 'left' | 'right'; mono?: boolean; muted?: boolean; width?: number | string };
export declare function DataTable<R>(p: { columns: Column<R>[]; rows: R[]; rowKey?: (r: R) => string | number; loading?: boolean; skeletonRows?: number; error?: string; onRetry?: () => void; empty?: { title?: string; description?: string }; toolbar?: React.ReactNode; footer?: React.ReactNode; onRowClick?: (r: R) => void; caption?: string }): React.ReactElement;
export declare function Pagination(p: { page: number; totalPages: number; total?: number; onPageChange?: (n: number) => void }): React.ReactElement;
export declare function DescriptionList(p: { title?: string; items: { term: string; value: React.ReactNode; mono?: boolean }[] }): React.ReactElement;
export declare function CodeBlock(p: { children: React.ReactNode; label?: string; maxHeight?: number }): React.ReactElement;
export declare function Disclosure(p: { summary: React.ReactNode; children?: React.ReactNode; defaultOpen?: boolean }): React.ReactElement;
export declare function FindingCard(p: { severity: 'critical' | 'major' | 'minor' | 'nit' | string; category?: string; location?: string; comment: React.ReactNode; suggestion?: string; blocking?: boolean; posted?: boolean }): React.ReactElement;
export declare function AccountCard(p: { displayName: string; login: string; avatarUrl?: string; repoCount: number; reconnectRequired?: boolean; syncing?: boolean; onResync?: () => void; installations?: { login: string; type: 'User' | 'Organization'; href?: string }[] }): React.ReactElement;
export declare function RepoGroup(p: { title: string; count?: number; children?: React.ReactNode }): React.ReactElement;
export declare function RepoRow(p: { fullName: string; enabled?: boolean; defaultEnabled?: boolean; onEnabledChange?: (v: boolean) => void; toggling?: boolean; lastEventAt?: string; removed?: boolean; onConfigure?: () => void }): React.ReactElement;
export declare function ProviderKeyRow(p: { provider: string; label?: string; isSet: boolean; saving?: boolean; onSave?: (value: string) => void }): React.ReactElement;
export type ChartTone = 'accent' | 'success' | 'warning' | 'error' | 'info' | 'highlight' | 'ink' | 'neutral';
export declare function BarChart(p: { data: Array<{ label: string } & Record<string, number | string>>; series: { key: string; label: string; tone: ChartTone; hatch?: boolean }[]; height?: number; format?: (v: number) => string; legend?: boolean; ariaLabel?: string }): React.ReactElement;
export declare function LineChart(p: { data: { label: string; value: number }[]; tone?: ChartTone; height?: number; format?: (v: number) => string; seriesLabel?: string; ariaLabel?: string }): React.ReactElement;
export declare function DonutChart(p: { data: { label: string; value: number; tone: ChartTone }[]; size?: number; centerLabel?: string; centerValue?: React.ReactNode; ariaLabel?: string }): React.ReactElement;
export declare function ChartLegend(p: { items: { label: string; tone: ChartTone; value?: React.ReactNode; hatch?: boolean }[] }): React.ReactElement;
export declare function ChartCard(p: { title: React.ReactNode; actions?: React.ReactNode; children?: React.ReactNode }): React.ReactElement;
export declare function LoginCard(p: { onSubmit?: (v: { email: string; password: string }) => void; loading?: boolean; error?: string | null; title?: string; subtitle?: string; defaultEmail?: string }): React.ReactElement;
